# Generated by Django 4.1 on 2022-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbooks',
            name='read_date',
            field=models.DateField(null=True),
        ),
    ]
