# Generated by Django 4.1 on 2022-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0002_alter_ownedbooks_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
