# Generated by Django 4.1 on 2022-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0002_alter_invoices_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
                ('entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('theme', models.CharField(max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('read_date', models.DateField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
                ('activity', models.CharField(max_length=40)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('time_when_done', models.DateTimeField()),
                ('task', models.CharField(max_length=40)),
                ('task_description', models.CharField(max_length=160)),
                ('expiration_date', models.DateTimeField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
