# Generated by Django 4.1 on 2022-09-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0003_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='time_when_done',
            field=models.DateTimeField(null=True),
        ),
    ]
