# Generated by Django 4.1 on 2022-09-03 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca', '0004_alter_todoitem_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('user', 'date')},
        ),
    ]
