# Generated by Django 4.1 on 2022-09-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0005_alter_journalentry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['date']},
        ),
    ]
