# Generated by Django 4.1 on 2022-09-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0006_alter_journalentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date']},
        ),
    ]
