# Generated by Django 4.1 on 2022-09-03 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca', '0008_alter_todoitem_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-time']},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('user', 'time')},
        ),
    ]
