# Generated by Django 4.1 on 2022-09-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0009_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
    ]
