# Generated by Django 4.1 on 2022-09-05 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca', '0010_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('user', 'time')},
        ),
    ]
