# Generated by Django 4.1 on 2022-08-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='log_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='log_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='log_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
